spring:
  application:
    name: account-service
  jackson:
    default-property-inclusion: non_null
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        default_schema: account
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog.yml
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

event:
  bootstrap-servers: ${KAFKA_URL}
  service-name: ${spring.application.name}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8765/eureka}
